services:
  - type: web
    name: ojutole
    runtime: node
    plan: free
    buildCommand: npm install --maxsockets=1 --prefer-offline --no-audit --no-fund && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
      - key: NPM_CONFIG_CACHE
        value: /tmp/.npm
